import turtle
tia = turtle.Turtle()
tia.penup()
tia.goto(40, 120)
tia.pendown()
tia.pensize(5)
tia.pencolor("black")

tia.fillcolor("khaki")
tia.begin_fill()
tia.forward(320)
tia.right(90)
tia.forward(240)
tia.right(90)
tia.forward(320)
tia.right(90)
tia.forward(240)
tia.right(90)
tia.end_fill()

tia.penup()
tia.goto(160, 80)
tia.pendown()

tia.fillcolor("gold")
tia.begin_fill()
tia.right(60)
tia.forward(200)
tia.right(120)
tia.forward(200)
tia.right(120)
tia.forward(200)
tia.end_fill()

tia.begin_fill()
tia.right(90)
tia.forward(170)
tia.right(90)
tia.forward(100)
tia.end_fill()
turtle.done()